Add features that closes issue #2014
js-fns/date-fns pull request #2037
Opened 2020-10-16 20:19 UTC by Beigelman

This pull request adds a new `yearStartsOn` option to the following functions:

- startOfQuarter, startOfYear

- endOfQuarter, endOfYear

- isSameQuarter, isSameYear

This new feature allows us to count the start of a year from another month than January. The `yearStartsOn` option is a number that can range from 0 to 11, with 0 representing January and 11 representing December.

It is not uncommon to have businesses that start tracking their yearly reports from another month than January. This functionality would save a lot of converting to and from the fiscal year.

Closes #2014

2020-10-27 04:19 UTC, kossnocorp requested changes
Great job, thank you 👍 Please address my comments

2020-10-27 04:19 UTC, kossnocorp commented on src/endOfQuarter/index.ts
> +  const month = currentMonth - diffToQuarterStartArray[currentMonth - (options ? options.yearStartsOn : 0)] + 3
If in the future we decide to add more options this will break. Please use `??` instead:

```suggestion
  const month = currentMonth - diffToQuarterStartArray[currentMonth - (options?.yearStartsOn ?? 0)] + 3
```

2020-10-27 04:19 UTC, kossnocorp commented on src/endOfQuarter/index.ts
> +  const diffToQuarterStartArray = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
Could you please add a short comment about what is this and also move it out of the function?

2020-10-27 04:19 UTC, kossnocorp commented on src/endOfYear/index.ts
> +  if (options) {
Same as above, if options change, this will break.

```suggestion
  if (typeof options?.yearStartsOn === 'number') {
```

2020-10-27 04:19 UTC, kossnocorp commented on src/isSameYear/index.js
> -import toDate from '../toDate/index'
Could you please recreate the commit so this file is renamed and not removed? This will make us lose all the history.

2020-10-27 04:19 UTC, kossnocorp commented on src/isSameYear/index.ts
> +  }
At the first glance, this is a weird condition. Why does it here?

2020-10-27 04:19 UTC, kossnocorp commented on src/startOfQuarter/index.ts
> +  const month = currentMonth - diffToQuarterStartArray[currentMonth - (options ? options.yearStartsOn : 0)]
```suggestion
  const month = currentMonth - diffToQuarterStartArray[currentMonth - (options?.yearStartsOn ?? 0)]
```

2020-10-27 04:19 UTC, kossnocorp commented on src/startOfQuarter/index.ts
> +  const diffToQuarterStartArray = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
Same here, please add a comment and move out of the function.

2020-10-27 04:19 UTC, kossnocorp commented on src/startOfYear/index.ts
> +  }
```suggestion
  date.setFullYear(cleanDate.getFullYear(), options.yearStartsOn ?? 0, 1)
```

2020-10-27 14:03 UTC, Beigelman commented on src/isSameYear/index.js
> -import toDate from '../toDate/index'
I'm not quite sure how to do that. I have tried several ways but all seem to get the same result where one file is deleted and another is created. I think this happens because git does not track file history [https://stackoverflow.com/questions/47571168/git-does-not-track-history-after-rename-move-of-modified-file](url) . The only solution I found was to separate into two different commits.

2020-10-27 18:09 UTC, Beigelman commented on src/isSameYear/index.ts
> +  }
This condition ensures that the `dirtydate` is within the `startTime` and the `endTime`. For example, if he calls
```js
 isSameYear('01-2020', '12-2020', { yearStartsOn: 3 })
```
he would check if `12-2020` is between `04-2020` and `03-2021` which is true but `01-2020` is not between this interval so it doesn't make sense. So this condition is to make sure that the `dirtydate` provided is inside the year offset otherwise this function with this option wouldn't make sense. I hope I made sense hehe. But I think the error message could be better I'm thinking of a better one

2021-04-09 16:05 UTC, zhirzh commented
i think `startOfYear` is not correct. if target date is "1st March 2020" and year start is set to "April" then target date's year should start on "1st April 2019" but current implementation returns "1st April 2020"

```js
var d = new Date(2020, 2, 1)
console.log(d.toString())
//> Sun Mar 01 2020 00:00:00 GMT+0530 (India Standard Time)

var x = startOfYear(d, { yearStartsOn: 3 }) // year starts on `April`
console.log(x.toString())
//> Wed Apr 01 2020 00:00:00 GMT+0530 (India Standard Time)  ---  incorrect

// correct value should be "Mon Apr 01 2019 00:00:00 GMT+0530 (India Standard Time)"
```

2026-05-18 14:49 UTC, closed without merging

2026-10-09 08:33 UTC, bfs2021 commented
@Beigelman @kossnocorp — I've taken this over in #4357, reimplemented on the current codebase with all the review feedback from here addressed (the `??` defaults, the commented quarter-start computation, and the per-function option docs), plus the year-boundary fix for the case @zhirzh reported. Thank you both — the original PR and review made this much easier to land.